#!/usr/bin/env bash
# Install and configure HAProxy load balancer

# Update packages
sudo apt-get update -y

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    daemon
    maxconn 100
    log /dev/log local0

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.83.140.35:80 check
    server web-02 18.234.165.101:80 check
EOF'

# Enable HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Start HAProxy
sudo systemctl restart haproxy

# Output to verify that the names web-01 and web-02 are used in the backend configuration
echo "Checking HAProxy configuration..."
curl -Is http://localhost | grep X-Served-By

echo "HAProxy installation and configuration complete. Traffic is now load balanced between web-01 and web-02."i
